DEFAULT:
  exp_name: forecasting_exchange_rate_96_24_noscale 
  seed: 42

DATASET:
  taskname: long_term_forecast
  dataname: custom
  sub_data_name: None
  scale: standard
  window_size: 336
  label_len: 0
  pred_len: 96
  model_type: forecasting
  pretrain: false
  split_rate: [0.7, 0.1, 0.2]
  timeenc: 0
  freq: h
  embed_type: learned

DATAINFO:
  datadir: ./dataset/ETT-small/ETTh1.csv
  train_path: 
  valid_path: 
  test_path: 
  test_label_path: 

TRAIN:
  epoch: 25
  batch_size: 64
  test_batch_size: 4
  num_workers: 0
  ckp_metric: MSE
  eval_epochs: 1
  log_epochs: 1
  log_eval_iter: 50
  shuffle: false
  pin_memory: true
  resume: false
  resume_number: 0
  early_stopping_metric: loss
  early_stopping_count: 20
  return_output: true
  lradj: type1
  wandb: 
    use: false
    iter: 50
    exp_name: default
    project_name: 'TMAE'
    entity: jinwoo

LOSS:
  loss_name: MSELoss

OPTIMIZER:
  opt_name: AdamW
  lr: 0.0001
  params:
    weight_decay: 0.0005

RESULT:
  savedir: './saved_model'