TimesNet:
  e_layers: 2
  d_layers: 1 
  enc_in: 8 
  dec_in: 8 
  c_out: 8 
  d_model: 96 
  d_ff: 64 
  top_k: 5 
  dropout: 0.1
  activation: gelu
  embed: timeF
  num_kernels: 6

DLinear:
  moving_avg: 25
  enc_in: 8 
  dropout: 0.1

TMAE:
  e_layers: 2
  d_layers: 1 
  factor: 3 
  enc_in: 8 
  dec_in: 8 
  c_out: 8 
  d_model: 96 
  d_ff: 64 
  top_k: 5 
  dropout: 0.1
  output_attention: None
  n_heads: 8
  activation: gelu
  embed: timeF

TMAE1:
  e_layers: 2
  d_layers: 1 
  factor: 3 
  enc_in: 8 
  dec_in: 8 
  c_out: 8 
  d_model: 96 
  d_ff: 64 
  top_k: 3
  dropout: 0.1
  output_attention: None
  n_heads: 8
  activation: gelu
  embed: timeF

TMAE2:
  e_layers: 2
  d_layers: 1 
  factor: 3 
  enc_in: 8 
  dec_in: 8 
  c_out: 8 
  d_model: 96 
  d_ff: 64 
  top_k: 5 
  dropout: 0.1
  output_attention: None
  n_heads: 8
  activation: gelu
  embed: timeF

TMAE3:
  e_layers: 2
  d_layers: 1 
  factor: 3 
  enc_in: 8 
  dec_in: 8 
  c_out: 8 
  d_model: 96 
  d_ff: 64 
  top_k: 5 
  dropout: 0.1
  output_attention: None
  n_heads: 8
  activation: gelu
  embed: timeF
