TimesNet:
  e_layers: 2
  d_layers: 1 
  enc_in: 125 
  dec_in: 125 
  c_out: 125 
  d_model: 16 
  d_ff: 64 
  top_k: 5 
  dropout: 0.1
  activation: gelu
  embed: timeF
  num_kernels: 6

DLinear:
  moving_avg: 25
  enc_in: 125 
  dropout: 0.1

TMAE1:
  e_layers: 2
  d_layers: 1 
  factor: 3 
  enc_in: 125 
  dec_in: 125 
  c_out: 125 
  d_model: 16 
  d_ff: 64 
  top_k: 3
  dropout: 0.1
  output_attention: None
  n_heads: 2
  activation: gelu
  embed: timeF

TMAE2:  
  patch_size: 3
  mask_ratio: 0.6
  stride: 12
  e_layers: 2
  d_layers: 1 
  factor: 3 
  enc_in: 125 
  dec_in: 125 
  c_out: 125 
  enc_d_model: 16
  dec_d_model: 16
  d_ff: 64 
  top_k: 10
  dropout: 0.1
  enc_n_heads: 2
  dec_n_heads: 1
  output_attention: None
  mode: pretrain
  activation: gelu
  embed: timeF
  mlp_ratio: 4

PatchTST:
  e_layers: 2
  d_layers: 1 
  factor: 3 
  enc_in: 125 
  dec_in: 125 
  c_out: 125 
  d_model: 16 
  d_ff: 64
  dropout: 0.1
  output_attention: None
  n_heads: 6
  activation: gelu
  embed: timeF

LLM4TS:
  patch_size: 20
  stride: 5
  channel_independence: True
  mode: DFT
  d_ff: 64
  d_model: 768
  gpt_layers: 6
  dropout: 0.1